export const REQUEST_ALL_ITEMS = "REQUEST_ALL_ITEMS";
export const REQUEST_ALL_ITEMS_SUCCESS = "REQUEST_ALL_ITEMS_SUCCESS";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const GET_CURRENT_ITEM = "GET_CURRENT_ITEM";
export const ADD_ITEM_TO_BASKET = "ADD_ITEM_TO_BASKET";
