export const REQUEST_ALL_ITEMS = "REQUEST_ALL_ITEMS";
export const REQUEST_ALL_ITEMS_SUCCESS = "REQUEST_ALL_ITEMS_SUCCESS";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const GET_CURRENT_ITEM = "GET_CURRENT_ITEM";
export const SET_FILTERED_ITEMS = "SET_FILTERED_ITEMS";
