export const GET_CURRENT_ORDER="GET_CURRENT_ORDER";
export const GET_CURRENT_ORDER_SUCCESS="GET_CURRENT_ORDER_SUCCESS";
export const UPDATE_ORDER="UPDATE_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";